# Generated by Django 2.1.5 on 2019-01-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190109_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
