# Generated by Django 2.1.5 on 2019-01-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
