# Generated by Django 2.1.5 on 2019-01-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20190110_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_order_price',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
